name: Run tests

  # push:
  #   branches:
  #     - master
  #     - development
  # pull_request:
  #   branches:
  #     - master
  #     - development

on:
  push:
    branches:
      - avoid_self_2

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://go:latest
        run: |
          go version
          ls
