name: Run tests


on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          go version
          go test -v test/*/**
