name: Run tests

  # push:
  #   branches:
  #     - master
  #     - development
  # pull_request:
  #   branches:
  #     - master
  #     - development

on:
  push:
    branches:
      - avoid_self_2

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: go:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a script
        run: |
          go version
          ls
